name: Update URLs Array

on:
  push:
    branches:
      - main

jobs:
  update-urls:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Find and update URLs
        run: |
          # Use find command to locate .html files and extract their URLs
          urls=$(find . -name "*.html" -exec grep -o 'http[s]*://[^"]*' {} \;)
          
          # Trim leading/trailing whitespace and convert to JSON array
          urls_json="[\"$(echo "$urls" | awk '{$1=$1;print}' | paste -sd '","' -)\"]"
          
          # Replace the existing array in urls.js
          sed -i "s|const urls = .*|const urls = $urls_json;|" my-random-projects/_index%20scripts/setup.js
          
          # Commit the changes
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add my-random-projects/_index%20scripts/setup.js
          git commit -m "Update URLs array"
          git push
          
